### ISSUE TITLE
NEED SPY HELPGalexy S5 & sneaky boyfriend i think..

### ISSUE THREAD

**Issue by liv4luvnus** [Humanise/onlineobjects#1]
Hello I am searching for help to recover Google map history dates that have been deleted. Also too find out where or what computer is hacked into my phone if that's possible and operating it from there. I am very new so be patient or at least have patience. And probably talk to me like a children's book with sound haha. Sorry just is what it is. I'd appreciate any help thank you

**Comment by liv4luvnus** [comment]
I'm very new, but trying to learn. Where would I merge the information given to fix my problem

**Comment by jonasmunk** [comment]
Hi, I am not sure why you have posted this issue here but you are clearly in the wrong place.

I hope you find help somewhere else.
